server:
  port: 9191

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhishekarya1/spring-cloud-config-server
          clone-on-start: true